### ISSUE TITLE
Cant leave terminal

### ISSUE THREAD

**Issue by CatsArmy** [Kyryh/FreeLookMonitor#1]
unsure why but when i enable your mod i cant leave the terminal no matter what i do

**Comment by Kyryh** [comment]
Can't seem to replicate. Can you give some more details?

**Comment by CatsArmy** [comment]
my modpack where i was trying out your mod it is atm disabled enable it to see what i mean
ill tell u if it stopped after i update my mods rn

[Cats Test pack  -Beta_1705946817204.zip](https://github.com/Kyryh/FreeLookMonitor/files/14013876/Cats.Test.pack.-Beta_1705946817204.zip)

**Comment by CatsArmy** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) Terminal.DMD<Terminal::QuitTerminal>(Terminal)
TerminalStuff.LeaveTerminal+Terminal_RunTerminalEvents_Patch+<PostfixCoroutine>d__4.MoveNext () (at <ca55161eb51b429399fa2114115ca5b9>:IL_0230)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

I really dont know why this is happening

**Comment by CatsArmy** [comment]
never mind it seems i have been able to narrow down the list of mods alot
will tell you soon but i dont think this is a you issue

**Comment by CatsArmy** [comment]
Ok so i found the mod...

[Mod Incompatibility]
https://thunderstore.io/c/lethal-company/p/Zaggy1024/TwoRadarMaps/

**Comment by Kyryh** [comment]
Thanks for the help. I've narrowed down the issue, will publish an update in an hour at most
