### ISSUE TITLE
[Suggestion] Option to zoom while tracking player

### ISSUE THREAD

**Issue by throwitaway99** [Kyryh/FreeLookMonitor#2]
Currently, as it stands, you initially free the camera by moving it, putting it in a sort of 'free' mode where it is no longer tracking the player the monitor is set to. It would be nice to have an option where, if you initially zoom *without* pressing any sort of movement keys, that it will allow you to zoom whilst tracking the player it is set to on the monitor.

**Comment by Kyryh** [comment]
I don't understand, are you asking for a way to zoom while still tracking a player? Because it already does that. The move and zoom features are indipendent from each other, you can always zoom without moving and vice versa.

**Comment by throwitaway99** [comment]
Oh hmm.. I'm not sure if there was some sort of conflict before, but I am unable to currently reproduce the issue I was having before. I will close this for now, and re-open if it resurfaces.
