### ISSUE TITLE
Does the mod still work?

### ISSUE THREAD

**Issue by welles** [Kyryh/FreeLookMonitor#3]
Hi there! This mod is very interesting!
Unfortunately I couldn't get it to work. I installed InputUtils and HookGenPatcher, and the keybinds show up in the InputUtils menu, but when I try to control the map nothing happens.
Is there something I'm missing? I tried it in the ship monitor and the terminal.

**Comment by Kyryh** [comment]
Can't seem to replicate, could you send the log file?
InputUtils and HookGenPatcher _should_ be all that you need, maybe there's a third dependency that i forgot about idk

Edit: Maybe a list of all the mods installed could also be useful, there may be compatibility issues

**Comment by welles** [comment]
I just tried it with only the three mods and it did not work unfortunately.
* HookGenPatcher 0.0.5
* InputUtils 0.6.2
* FreeLookMonitor 1.0.1

This was the output generated by BepInEx:
```
[Message:   BepInEx] BepInEx 5.4.22.0 - Lethal Company (25.12.2023 15:42:58)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Lethal Company Input Utils 0.6.2]
[Info   :Lethal Company Input Utils] Registered InputUtilsExtendedMouse Layout Override!
[Info   :Lethal Company Input Utils] InputUtils 0.6.2 has finished loading!
[Info   :   BepInEx] Loading [FreeLookMonitor 1.0.1]
[Message:   BepInEx] Chainloader startup complete
```

Important to note is: I only tried it by myself playing solo. Does it maybe not work when the monitor is centered on yourself in the ship, and not on another player in the facility? If so, I will install the mod for the next session with my friends and test it with them.

**Comment by Kyryh** [comment]
Seems like it isn't loading HookGenPatcher for some reason, make sure that it's in the patchers folder and not in the plugins folder

The mod should work even in solo, so that's not an issue

**Comment by welles** [comment]
Aw man! 😆 Thanks for your help, I had HookGenPatcher in the plugins folder all this time! Now the mod works!

**Comment by Kyryh** [comment]
No problem
I'd suggest using r2modman for using mods since It automstically installa the dependencies and puts them in the right folders for you
